name: checks

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
          cache: pip
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: for test in test_*.py; do python "$test"; done
      - run: pyright
      - run: ruff check
      - run: pip check
